### ISSUE TITLE
Project Edit Page

### ISSUE THREAD

**Issue by Splitbreed** [adammpolak/turnuptimesystem#10]
Page Route: `/projects/:pId/edit`

UPDATEs a specific project. Allows the user to edit the description, title, create and change tasks within the project.

**Comment by Splitbreed** [comment]
On the Project Details page, the user has the option of clicking edit to update the project's name, description, or add tasks (and task name and description as well). The user can also delete the entire project  #6

**Comment by RBeneroff** [comment]
and /projects/new 

   - all fields required

**Comment by Splitbreed** [comment]
@RBeneroff #8

**Comment by Splitbreed** [comment]
Completed
