### ISSUE TITLE
Overall User Story

### ISSUE THREAD

**Issue by RBeneroff** [adammpolak/turnuptimesystem#6]
When the user visits TurnUpTimeSystem's home page the user has the choice of signing up or logging in. A user cannot use or view the rest of the app until logging in.

Once logged in, the user is brought to their User Home page. The User Home page consists of a nav bar (projects, completed projects, account), and a list of all the projects in the database. If a user is working on one of these projects, they can click the project and will be brought to that project's detail page. If there are no current projects or the user needs to create a new project, they can click the Create Project button. #16

On the Project Details page, the user has the option of clicking edit to update the project's name, description, or add tasks #17 (and task name and description as well). The user can also delete the entire project here. If the user would like to start tracking their time, they can click the play button next to the task they are working on. When the user is done working on that project for that time period, they can click the stop button. Every task will display the total amount of time spent on each specific task (total, non-specific to user) as well as an overall time with the total hours spent on the project.
   - Project Details page also shows the name of the user that created it

When a projected is completed, the user can click the Completed Project button and the project will move to the Completed Projects archive page. If a user realizes that the project is not yet completed, they can go to the completed projects and un-click the button for a specific project which will move the project back to the user's home page. (the Completed Project button will be on the User's home page where it has the list of all the current projects)

**Comment by RBeneroff** [comment]
Wait, where do we create a new project?
Also, is each task displaying the total time worked on? If so, is it for THAT user's time or the time for all the users who worked on that task? -- or is each task specific to the user while projects is global to everyone?

**Comment by Splitbreed** [comment]
Everything fulfilled.
